name: My Python Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python inference_text2image.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Inject GitHub secret as an environment variable
        INFERENCE_CLIENT_MODEL: ${{ secrets.INFERENCE_CLIENT_MODEL }}
